# Generated by Django 3.1.7 on 2021-03-09 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=256)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('time_reminder', models.TimeField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1)),
                ('day_of_week', models.ManyToManyField(to='myrem.DayOfWeek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('s', 'success'), ('f', 'fail')], max_length=10)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrem.reminder')),
            ],
        ),
    ]
